### PR TITLE
Issue #361: Adds a test that checks if a student can only belong in a…

### PR DESCRIPTION
**Pull request by pedrorolo**
Adds a test to grade-school testing that a Student cannot belong in two different grades. Following up the discussion on Issue #361.

### CODE REVIEW

**Comment by pedrorolo** [comment]
I've also created [a PR on the problems-specifications track](https://github.com/exercism/problem-specifications/pull/1735).

**Comment by glennj** [comment]
Does the example solution pass this test? If not, this PR should update the example.

**Comment by pedrorolo** [comment]
> Does the example solution pass this test? If not, this PR should update the example.

It was not passing. I've updated the example and squashed these additions into the PR branch. The updated example is the solution I developed for the exercise when I stumbled upon this issue.

**Review by SleeplessByte — APPROVED** [review]
Thank you very much for entertaining the conversation about this and making the necessary changes @pedrorolo

**Pull request merged**
