### PR TITLE
fix typos in accumulate.test.ts

### PR DESCRIPTION
**Pull request by emiller42**
fixes exercism/typescript#211

### CODE REVIEW

**Comment by masters3d** [comment]
How were tests passing before?

**Comment by masters3d** [comment]
Good catch, could you update the makefile so it doesn’t happen again?

https://github.com/exercism/typescript/blob/39b78394df8e7afd947f43dbe92c6748442cbbfd/Makefile#L20

**Comment by emiller42** [comment]
Hmm, appears that sed is behaving differently in circleci as is does locally. Tests are now skipping.  Digging into that...

**Comment by masters3d** [comment]
Oh macos' sed does not replace in place.

**Comment by masters3d** [comment]
Can you add gnu sed to the macos build? https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities

**Comment by masters3d** [comment]
Thanks! I'll submit a change for the macos in another PR.

**Comment by masters3d** [comment]
Its cool! I think making macOS sed work in a more portable way is a little better for maintenance.

**Pull request merged**
