### PR TITLE
Inline the exercise README insert

### PR DESCRIPTION
**Pull request by kytrinyx**
Now that we're operating with a track-wide template for generating exercise
READMEs we no longer need a separate markdown document to use for hints
and instructions that apply to all the exercises in a track. These instructions
can be defined directly in the template.

The first commit regenerates the exercise READMEs to pick up tweaks to problem descriptions, which have been updated with various formatting changes, whitespace changes, and clarifications to the description.

That gives us a clean diff when inlining the template and regenerating.

Ref: https://github.com/exercism/meta/issues/94

### CODE REVIEW

**Comment by masters3d** [comment]
- [ ] Decide where the HelloWorld tutorial should go.

**Comment by kytrinyx** [comment]
I would suggest `exercises/hello-world/.meta/hints.md` - that will get it automatically included into the README when you regenerate it with `configlet generate . --only=hello-world --path-spec=../path/to/problem-specifications`

**Comment by masters3d** [comment]
Good point. We will need to do this after this PR.

**Comment by kytrinyx** [comment]
No, if we do it after then we'll lose it if we deploy this before the change happens. I'll do it as part of this one.

**Comment by kytrinyx** [comment]
I've extracted the setup and tutorial. This should be good to merge now.

**Comment by masters3d** [comment]
Thank you

**Pull request merged**
