### PR TITLE
import() causing TS to throw method on type error

### PR DESCRIPTION
**Pull request by thedevelopnik**
Having trouble getting it to recognize methods on the dynamically imported class.

See comments on https://github.com/exercism/typescript/issues/121

### CODE REVIEW

**Comment by masters3d** [comment]
try changing the module target to esnext

```
Many bundlers have support for automatically splitting output bundles based on these import expressions, so consider using this new feature with the esnext module target.
```

**Comment by masters3d** [comment]
https://github.com/exercism/typescript/blob/7c30725653987323fb10d397935689cc5cc31f61/common/tsconfig.json#L3

**Comment by masters3d** [comment]
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by masters3d** [comment]
also module needs to be esnext

https://github.com/exercism/typescript/blob/7c30725653987323fb10d397935689cc5cc31f61/common/tsconfig.json#L4

**Comment by masters3d** [comment]
Reopen when you get a chance to work on it :)

**Comment by thedevelopnik** [comment]
Yep, sorry, that's today.

Changed the `target` and `module` props to `esnext` in tsconfig.json. That did get it a step further, but hit a new roadblock. This feature seems to be made more for dynamically importing guaranteed resources than for contingently importing resources that may be missing. If you delete `acronym.example.ts` or remove all code that exports anything (from that or `acronym.ts`), then TS won't compile because the module doesn't exist.

Since the point of the story was to allow it to import someone's work once they'd gotten rid of, or in the absence of, the example, I don't think this will fulfill that goal, so I'm going to leave it closed for now unless I have an epiphany.

**Pull request closed without merging**
