### PR TITLE
feat: added the tournament exercise

### PR DESCRIPTION
**Pull request by BrianDGLS**
Hi,

I've added the Tournament exercise. This is the first exercise I've committed, so let me know if there are any issues and I can resolve them.

Also if there is a list of exercise that you would like added by priority then I can take a look at those too. Assuming this one goes well.

Thanks,

Brian

### CODE REVIEW

**Comment by BrianDGLS** [comment]
Also I added the config based of the C# repo, so the uuid maybe wrong.

**Comment by SleeplessByte** [comment]
> Also I added the config based of the C# repo, so the uuid maybe wrong.

Do you mean you copied it? If yes, please generate a new UUID v4 :)

**Comment by BrianDGLS** [comment]
> Do you mean you copied it? If yes, please generate a new UUID v4 :)

Yep, I have updated the UUID. Any other changes required?

Thanks.

**Comment by BrianDGLS** [comment]
@SleeplessByte Hi, any update on the status of this PR? I'd like to look at adding other exercises, should this be accepted.

**Comment by SleeplessByte** [comment]
I completely missed this! Sorry.

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
It's been good for a month!! Sorry I didn't get to this sooner. Feel free to ping me earlier or find me on slack.

**Comment by BrianDGLS** [comment]
Thanks @SleeplessByte

**Pull request merged**
