### PR TITLE
add kindergarten exercise

### LINKED ISSUE #101: implement kindergarten garden
As per #37, port exercise from ecmascript track

### PR DESCRIPTION
**Pull request by fredrb**
Fixes #101

### CODE REVIEW

**Comment by CRivasGomez** [comment]
This is looking great @fredrb, thanks for adding this exercise! 🙂

It looks like you forgot adding the new exercise to `config.json`.
Feel free to ask questions 🙂

**Comment by fredrb** [comment]
Looks like it. My bad. Thanks!

**Comment by masters3d** [comment]
We need to figure out how to expose the errors from the make file in Danger. The thing is now we just die if any of those checks fail which then doesn’t trigger danger. Not sure how to solve it or just leave it alone.

**Comment by CRivasGomez** [comment]
I will be trying to figure out how to expose errors.

**Comment by CRivasGomez** [comment]
Good job @fredrb ☺

**Pull request merged**
