### PR TITLE
Add new exercise Two Fer

### PR DESCRIPTION
**Pull request by CRivasGomez**
Hey!
I added Two Fer exercise 🙂

### CODE REVIEW

**Comment by masters3d** [comment]
Thanks!

**Comment by masters3d** [comment]
Would you be interested in becoming a contributor? If so, @kytrinyx  How do I add people as contributors: 
image

**Comment by CRivasGomez** [comment]
Cool! I really like this project. It would be great to participate as a contributor 🙂

**Comment by kytrinyx** [comment]
@CRivasGomez 🎉 thank you! I've sent you an invite

**Pull request merged**
