### PR TITLE
 difference-of-sums: renamed squareOfSums to squareOfSum 

### PR DESCRIPTION
**Pull request by Scientifica96**
In exercise "difference-of-sums", renamed `squareOfSums` to `squareOfSum`, and some instances of sums to sum. Modified version number as well.

### CODE REVIEW

**Comment by masters3d** [comment]
Is this like maths vs math?

**Comment by Scientifica96** [comment]
I don't think so. See the discussion [here](https://github.com/exercism/haskell/pull/711) about the same issue in the Haskell repository.

**Comment by masters3d** [comment]
Sounds good. Remove the last commit and we will merge.

**Comment by Scientifica96** [comment]
Ok canceled the change in version number.

**Comment by masters3d** [comment]
Thanks!

**Comment by Scientifica96** [comment]
It's a pleasure :D

**Pull request merged**
