### PR TITLE
Remove explicit type anotations for inferrable types

### PR DESCRIPTION
**Pull request by Roshanjossey**
Refer conversation in #291 for information about this change

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@Roshanjossey can you do the others in THIS PR as well?

Re: your question:

https://github.com/exercism/typescript#shared-code

You can use https://github.com/exercism/typescript/blob/master/Makefile#L113-L123 to sync configurations to each exercise!

**Comment by Roshanjossey** [comment]
Hi @SleeplessByte, just to be on the same page here, could you please confirm if my assumptions are correct?


 * Danger bot (pacman-bot) uses [typescript-analyzer](https://github.com/exercism/typescript-analyzer)
 * The configurations in the exercise directories are used when users use exercism commandline and doing the exercises.

`make test` still throws errors in my local. So, please check at your end before merging this PR.

I'm still not comfortable with how yarn commands works in the individual exercises but we can talk about it in the prettier PR.

**Comment by SleeplessByte** [comment]
> Danger bot (pacman-bot) uses typescript-analyzer

No, it uses `danger`. The [Dangerfile](https://github.com/exercism/typescript/blob/master/Dangerfile) is executed on the `eslint` report (generated with `make report`) when we call `danger`, which is what we do [on Travis](https://github.com/exercism/typescript/blob/master/.travis.yml#L22-L23).

> The configurations in the exercise directories are used when users use exercism commandline and doing the exercises.

The `exercism` cli tool has nothing to do with any "local" configuration files. But `exercism download` will indeed download "the entire exercise directory" **except** for any `.meta` folder or any `example.ts` file.

> I'm still not comfortable with how yarn commands works in the individual exercises but we can talk about it in the prettier PR.

I don't know what this means, but sure 😄

**Comment by SleeplessByte** [comment]
> make test still throws errors in my local. So, please check at your end before merging this PR.

@Roshanjossey Could you be so kind and attach that output? Or what are the errors you see?

**Comment by Roshanjossey** [comment]
This is what `eslint . --ext .tsx,.ts` returns when it's run as a part of `make test`

``` 
$ eslint . --ext .tsx,.ts

/tmp/tmp.dFNk9Uuwxk/beer-song.ts
  28:22  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types
  28:40  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types

/tmp/tmp.dFNk9Uuwxk/clock.ts
  5:29  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types

/tmp/tmp.dFNk9Uuwxk/pangram.ts
  7:15  error  Type string trivially inferred from a string literal, remove type annotation  @typescript-eslint/no-inferrable-types

/tmp/tmp.dFNk9Uuwxk/pythagorean-triplet.ts
  35:34  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types

/tmp/tmp.dFNk9Uuwxk/robot-simulator.ts
  5:15  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types
  5:35  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types
  5:55  error  Type string trivially inferred from a string literal, remove type annotation  @typescript-eslint/no-inferrable-types

✖ 8 problems (8 errors, 0 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.```

**Comment by SleeplessByte** [comment]
The tmp folder was probably not cleared correctly :)

**Comment by Roshanjossey** [comment]
Tried with clearing everything from `/tmp` with the same results.

Could you try this branch on your local?

**Comment by SleeplessByte** [comment]
Yep. Pulling it and trying it out.

**Comment by SleeplessByte** [comment]
Did a fresh clone and everything was ✔️ after I copied the shizzle to `maintainers/.eslint.track.rc`

**Comment by Roshanjossey** [comment]
Awesome. Thank you @SleeplessByte :heart:

**Pull request merged**
