### PR TITLE
Fixes smal typo

### PR DESCRIPTION
**Pull request by meatball133**
fixes https://github.com/exercism/typescript/issues/1176

### CODE REVIEW

**Comment by angelikatyborska** [comment]
This mistake comes from the shared central repository from which all Exercism tracks get test definitions. It was also already fixed there, see: https://github.com/exercism/problem-specifications/blob/main/exercises/largest-series-product/canonical-data.json#L177-L203

The fix chosen there is to change the error message to `"span must not be negative"`

To mark that the exercise's tests have been updated to match the central repository, it's also necessary to run those commands:
```
./bin/fetch-configlet 
./bin/configlet sync --update --tests=include --yes --exercise largest-series-product
```

The second command will create some changes to the file `exercises/practice/largest-series-product/.meta/tests.toml` which also need to be commited in.

**Comment by meatball133** [comment]
I should have closed this pr since a while ago. I am aware of that changes goes through problem spec repo.

**Comment by angelikatyborska** [comment]
@meatball133 You could also fix it, right? It doesn't require a lot of work. But if you close it, I can open my own PR for the same issue.

**Comment by meatball133** [comment]
Okay fixed it @angelikatyborska.

**Review by angelikatyborska — APPROVED** [review]
Perfect 👍 

@SleeplessByte this one looks good to merge to me

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
Thank you both ❤️

**Pull request merged**
