### PR TITLE
Fix precision in space-age tests

### PR DESCRIPTION
**Pull request by texastoland**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Can you be explicit and [supply the second parameter][ref] to the [`toBeCloseTo`][ref] call? I think it should be `2`, since we're expecting 2 digits after the decimal.

[ref]: https://github.com/facebook/jest/blob/05b8382751b06c08113d81de757976740d4d32bf/website/versioned_docs/version-22.x/ExpectAPI.md#tobeclosetonumber-numdigits

**Comment by texastoland** [comment]
I didn't originally because it's the default 👍🏽

**Comment by SleeplessByte** [comment]
Yeah that makes sense. I'm just weary that if that default ever changes (major version bump) we would have to change this too 😅

**Comment by SleeplessByte** [comment]
However, I'm looking at 

https://github.com/exercism/typescript/blob/4c27c708f79677f253034c692dbb92ca539fe365/exercises/space-age/space-age.example.ts#L9

And [the mentor notes][notes]

```javascript
export function age(planet, earthAgeInS) {
  return Number((earthAgeInS / EARTH_YEAR_IN_S / getOrbitalPeriod(planet)).toFixed(2))
}
```

And it seems that this change removes the need to do `.toFixed` or round, which is one of the teaching subjects of this exercise. Is that correct?

[notes]: https://github.com/exercism/website-copy/blob/064e8843fd81abc56b65213fcda5a58c999f2ebf/tracks/javascript/exercises/space-age/mentoring.md

**Comment by texastoland** [comment]
Correct. I didn't know about the notes. I prefer to delete that line and add one under the changelog heading. Would that be acceptable?

**Comment by SleeplessByte** [comment]
> Would that be acceptable?

Will this remove the *need* for rounding? I think we'd like to preserve that in this exercise!

**Comment by texastoland** [comment]
> Will this remove the _need_ for rounding?

Precisely.

> I think we'd like to preserve that in this exercise!

I don't see your reasoning.

1. There's no mention of rounding in the instructions.
2. The other tracks expect the output not rounded.
3. You never round function output in general. We use formatters for that.
4. It defeats my understanding of the point of Exercism which is to develop algorithmic reasoning.

I was using Exercism to mentor my team and recommended it to the candidates I interview. I ran into this bug. If you feel like it's not a bug, you're welcome to close it.

**Comment by SleeplessByte** [comment]
> There's no mention of rounding in the instructions.

This is definitely something we can change ✨ and I think that's a _fair_ change too.

> The other tracks expect Space Age's output not rounded.

I picked the first 6 that I had in my auto-completion:

- C# rounds the answer to precision 2 and then compares
- [Java][java] expects it to be rounded and equal, with at most `10^-2` difference
- [JavaScript][javascript] expects it to be rounded to 2 digits
- [Kotlin][kotlin] expects it to be rounded to 2 digits
- [Ruby][ruby] expects it to be rounded and equal, with at most `0.01` difference
- [Rust][rust] expects it to be rounded and equal, with at most `0.01` difference

> You never round function output in general. We use formatters for that.

This is a statement that is factually untrue, on both accounts.

> It defeats a key point of Exercism which is to focus on algorithmic reasoning.

The goal of exercism is to [achieve fluency in a (new) language](https://exercism.io/values#fluency)

> I was using Exercism to mentor my team and recommend it to the candidates I interview. I ran into this bug. If you feel like it's not a bug, you're welcome to close it.

It is not a bug, but after your last response I think the problem is mostly with the [problem-specification][pd]. As you can see, the canonical data is defined as expecting 2 decimal places. 

We can definitely do one of these things:

- Add the appropriate language to the description; with a note that some tracks will need to update the code to *remove* automatic rounding
- Add the appropriate language to *this* track (and at least the ones above except for c#) via a hints file
- Change the canonical data, that is, add a comment there to each test case that the test generator _should round the output_.

I understand what you're saying and I'm not an authority on what the exercise ultimately should be like, so I'd like to keep this open as to not throw away your work. I suggest you open an issue in the problem specification repository to discuss this further. You may link back to this and simply copy the initial message and this conversation. 

[ruby]: https://github.com/exercism/ruby/blob/master/exercises/space-age/space_age_test.rb#L14
[java]: https://github.com/exercism/java/blob/master/exercises/space-age/src/test/java/SpaceAgeTest.java#L14
[javascript]: https://github.com/exercism/javascript/blob/master/exercises/space-age/space-age.spec.js#L5
[kotlin]: https://github.com/exercism/kotlin/blob/master/exercises/space-age/src/test/kotlin/SpaceAgeTest.kt#L11
[rust]: https://github.com/exercism/rust/blob/master/exercises/space-age/tests/space-age.rs#L17
[pd]: https://github.com/exercism/problem-specifications/tree/master/exercises/space-age

**Comment by masters3d** [comment]
Can we accept this? It looks fine to me.

**Comment by SleeplessByte** [comment]
Not until I've spoken with @F3PiX.

**Comment by texastoland** [comment]
> I picked the first 6 that I had in my auto-completion:

That's surprising. Haskell, OCaml, and Bash didn't.

> This is a statement that is factually untrue, on both accounts.

I agree to disagree.

> The goal of Exercism is to achieve fluency in a (new) language

I stand corrected. I consider `toFixed(n)` a corner case rather than language fluency. Regardless, it might be more intuitive in a problem involving percents or dollars and cents with intrinsic precision.

> I think the problem is mostly with the [problem-specification](https://github.com/exercism/problem-specifications/tree/master/exercises/space-age)

I disagree. Floating point numbers are historically troublesome in general. It's impossible to encode the exact IEEE result as a string. Therefore the canonical data had to approximate to some precision.

> I suggest you open an issue in the problem specification repository to discuss this further.

I leave it to the maintainers to do what suits them.

**Comment by SleeplessByte** [comment]
Whilst I agree with the statement...

> Regardless, it might be more intuitive in a problem with intrinsic precision like percents or dollars and cents.

...I've checked the Track Anatomy tool and _because we don't have another exercise in the core track_ that deals with rounding, the tool tells me to leave this in the exercise. I'm happy to revisit this change (and merge it instantly) once we have a dedicated exercise as such in the core.

**Pull request closed without merging**
