### PR TITLE
Feature/alphametics

### LINKED ISSUE #98: implement alphametics
As per #37, port exercise from ecmascript track

### PR DESCRIPTION
**Pull request by W0lfw00d**
This is my first attempt (wip?) at trying to resolve #98

I haven't used TypeScript for very long, so this is as much a learning thing for me as it is trying to help....

### CODE REVIEW

**Comment by masters3d** [comment]
It has not much to do with the space.  If you look at the error on the CI it says that all files need to match the common folder. Try coping these files straight from the common folder.

**Comment by W0lfw00d** [comment]
That is what I did. 😞 But the only difference is some whitespace characters which my editor removed after saving.

**Comment by masters3d** [comment]
I don’t know then. Are you in windows? 

Replace all the files in common with out opening them? 


/make checkAllPackageFilesAreTheSame
make[2]: *** [checkPackageFilesMach] Error 1
**Package files in |alphametics| are not equal to the |common| folder**
make[2]: *** [reportError] Error 1
make[1]: *** [checkAllPackageFilesAreTheSame] Error 1
make: *** [test] Error 2
Exited with code 2

**Comment by masters3d** [comment]
almost there. now anagram is the issue

**Comment by masters3d** [comment]
```
 FAIL  ./alphametics.test.ts (67.954s)
  Solve the alphametics puzzle
    ✕ puzzle with three letters (184ms)
    ✓ solution must have unique value for each letter (1ms)
    ✓ leading zero solution is invalid (41ms)
    ✕ puzzle with four letters (23ms)
    ✕ puzzle with six letters (991ms)
    ✕ puzzle with seven letters (4694ms)
    ✕ puzzle with eight letters (16505ms)
    ✕ puzzle with ten letters (43297ms)

  ● Solve the alphametics puzzle › puzzle with three letters

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"B": 9, "I": 1, "L": 0}
    Received:
      undefined
    
    Difference:
    
      Comparing two different types of values. Expected object but received undefined.
      
      at Object.it (alphametics.test.ts:11:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Solve the alphametics puzzle › puzzle with four letters

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"A": 9, "M": 1, "O": 0, "S": 2}
    Received:
      undefined
    
    Difference:
    
      Comparing two different types of values. Expected object but received undefined.
      
      at Object.it (alphametics.test.ts:32:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Solve the alphametics puzzle › puzzle with six letters

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"A": 0, "E": 2, "L": 1, "N": 7, "O": 4, "T": 9}
    Received:
      undefined
    
    Difference:
    
      Comparing two different types of values. Expected object but received undefined.
      
      at Object.it (alphametics.test.ts:45:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Solve the alphametics puzzle › puzzle with seven letters

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"E": 4, "G": 2, "H": 5, "I": 0, "L": 1, "S": 9, "T": 7}
    Received:
      undefined
    
    Difference:
    
      Comparing two different types of values. Expected object but received undefined.
      
      at Object.it (alphametics.test.ts:59:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Solve the alphametics puzzle › puzzle with eight letters

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"D": 7, "E": 5, "M": 1, "N": 6, "O": 0, "R": 8, "S": 9, "Y": 2}
    Received:
      undefined
    
    Difference:
    
      Comparing two different types of values. Expected object but received undefined.
      
      at Object.it (alphametics.test.ts:74:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Solve the alphametics puzzle › puzzle with ten letters

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"A": 5, "D": 3, "E": 4, "F": 7, "G": 8, "N": 0, "O": 2, "R": 1, "S": 6, "T": 9}
    Received:
      undefined

    
    Difference:
    
      Comparing two different types of values. Expected object but received undefined.
      
      at Object.it (alphametics.test.ts:91:45)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       6 failed, 2 passed, 8 total
Snapshots:   0 total
Time:        69.067s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by masters3d** [comment]
Thanks!

**Pull request merged**
