### PR TITLE
Address #250 Normalise topics

### PR DESCRIPTION
**Pull request by Roshanjossey**
Fix topics for `diamond`, `two-buckets` and `variable-length-quantity`

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Don't mind these warnings :)

**Comment by Roshanjossey** [comment]
Hi @SleeplessByte, I see that the errors are caused by explicitly adding types when it's not necessary.

Shall I submit a pull request to address this?

**Comment by SleeplessByte** [comment]
We probably want to fine-tune `@typescript-eslint/no-inferrable-types` first. I'll accept a PR to add these lines https://github.com/exercism/javascript-analyzer/blob/master/.eslintrc#L42-L46, which will solve most of them.

**Comment by Roshanjossey** [comment]
Got it. 

Should this change be made in https://github.com/exercism/typescript-analyzer/blob/master/.eslintrc or individual `.eslintrc` in project directories? Is there a mechanism by which these are synced?

**Comment by Roshanjossey** [comment]
Also, even with the change you suggested 

> add these lines https://github.com/exercism/javascript-analyzer/blob/master/.eslintrc#L42-L46, 

We need to fix these as these are properties, won't we?

**Pull request merged**
